name: Build And Release

on:
  push:
    branches:
      - master


      #build docker file
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/apple-montior:${{ github.sha }}
            - name: Log in to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Push image to Docker Hub
              run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/apple-montior:${{ github.sha }}

        